version: '3.8'

services:
  merchant-db:
    image: postgres:17
    container_name: merchant_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: merchant_management
    volumes:
      - "./containers/merchant_db/:/var/lib/postgresql/data"
    ports:
      - "5435:5432" # Exposed on port 5435 locally