services:
  db:
    image: postgres:17
    container_name: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
    volumes:
      - "./infrastructure/db/:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped

    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - "./infrastructure/rabbitmq_data:/var/lib/rabbitmq"
  my-keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KC_HTTP_RELATIVE_PATH: /auth
      KC_HOSTNAME: localhost
      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 15s
      timeout: 2s
      retries: 15
    depends_on:
      db:
        condition: service_healthy
    command: ["start-dev", "--http-port", "8080", "--https-port", "7443"]
    ports:
      - "8080:8080"
      - "7443:7443"
  gateway:
    image: just-pay.gateway
    container_name: just-pay.gateway
    build:
      context: ./backend/JustPaymentSystem.Gateway
      dockerfile: Dockerfile
    ports:
      - 5055:5055
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=5055
      # Keycloak
      - Keycloak__Authority=http://keycloak:8080/realms/just-pay
      - Keycloak__ClientId=gateway
      - Keycloak__Audience=account
      - Keycloak__Issuer=http://keycloak:8080/realms/just-pay
      - Keycloak__MetadataAddress=http://keycloak:8080/realms/just-pay/.well-known/openid-configuration

      # Merchant Service
      - ReverseProxy__Clusters__merchantCluster__Destinations__mercahntService__Address=http://just-pay.merchant:5019/

      # Transaction Service
      - ReverseProxy__Clusters__transactionCluster__Destinations__transactionService__Address=http://just-pay.transaction:5153/

      # Keycloak
      - ReverseProxy__Clusters__keycloakCluster__Destinations__authService__Address=http://keycloak:8080/

      # Frontend
      - ReverseProxy__Clusters__clientCluster__Destinations__clientService__Address=http://just-pay.client:80
  transactions:
    image: just-pay.transaction
    container_name: just-pay.transaction
    build:
      context: ./backend/JustPaymentSystem.Transactions/src
      dockerfile: Dockerfile
    ports:
      - 5153:5153
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5153
      - ConnectionStrings__Default=Host=db;Port=5432;Database=transaction;Username=postgres;Password=postgres

      - Keycloak__Authority=http://keycloak:8080/realms/just-pay
      - Keycloak__ClientId=merchant-service
      - Keycloak__Audience=account
      - Keycloak__Issuer=http://keycloak:8080/realms/just-pay
      - Keycloak__MetadataAddress=http://keycloak:8080/realms/just-pay/.well-known/openid-configuration

      - ApiGateway__BaseAddress=http://just-pay.gateway:5055

      - Client__Url=http://just-pay.client:80

      - RabbitMq__Uri=amqp://admin:admin123@rabbitmq:5672
  merchant:
    image: just-pay.merchant
    container_name: just-pay.merchant
    build:
      context: ./backend/JustPaymentSystem.Merchant
      dockerfile: Dockerfile
    ports:
      - 5019:5019
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5019
      - ConnectionStrings__Default=Host=db;Port=5432;Database=merchant_management;Username=postgres;Password=postgres

      - Keycloak__Authority=http://keycloak:8080/realms/just-pay
      - Keycloak__ClientId=merchant-service
      - Keycloak__Audience=account
      - Keycloak__Issuer=http://keycloak:8080/realms/just-pay
      - Keycloak__MetadataAddress=http://keycloak:8080/realms/just-pay/.well-known/openid-configuration

  webhook:
    image: just-pay.webhook
    container_name: just-pay.webhook
    build:
      context: ./backend/JustPaymentSystem.WebHook
      dockerfile: Dockerfile
    ports:
      - 5074:5074
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5074
      - RabbitMq__Uri=amqp://admin:admin123@rabbitmq:5672
  frontend:
    build:
      context: ./client/just-payment-system
      dockerfile: Dockerfile
    container_name: just-pay.client
    ports:
      - "8081:80"
    restart: unless-stopped
